Fixing RAM calculator and reduced actual SRAM usage
- Changed static variables to const that should have been const
- Updated CMake files to prepare for MCHCK custom bootloader
- Changed the USB ID numbers and ID number for bootloader
- Only generate DFU or Teensy binary image, not both
- Fixed RAM and FLASH calculator
- Added missing license in delay.c/h (much of it was taken from Teensy source though I've changed a bunch of it)
- Prepared mk20dx.c for upcoming bootloader addition
- mk20dx.h cleanup
- Reduced the MCHCK based flash size for the application image (bootloader changes requires more flash space)
- Fixed bugs in macro.c
- Added keyHold cli command
- Added show pending events debug message for PartialMap macro module

diff --git a/Lib/CMake/sizeCalculator b/Lib/CMake/sizeCalculator
--- a/Lib/CMake/sizeCalculator
+++ b/Lib/CMake/sizeCalculator
@@ -2,15 +2,24 @@
 #| Jacob Alexander 2014
 #| Arg List
 #| 1 - size binary   (e.g. avr-size)
-#| 2 - target binary (e.g. ihex)
+#| 2 - measurement type (flash or ram)
 #| 3 - binary file   (e.g. kiibohd.hex)
 #| 4 - total available (flash/ram) in bytes
-#| 5 - flash/ram
+#| 5 - flash/ram text
 
 
-# Looks for the data column, to get the flash/ram used (in bytes)
-# <size binary> --target=<target binary> <binary file> | cut -f2 | tail -n 1
-USED=$("$1" --target="$2" "$3" | cut -f2 | tail -n 1)
+case "$2" in
+"flash")
+	USED=$("$1" "$3" | tail -n-1 | awk '{ print $1+$2 }')
+	;;
+"ram")
+	USED=$("$1" "$3" | tail -n-1 | awk '{ print $2+$3 }')
+	;;
+*)
+	echo "INVALID Measurement type: $2"
+	exit 1
+esac
+
 
 # Calculates the total flash/ram used
 TOTAL="$4"
@@ -35,7 +44,7 @@ fi
 
 # Displays Results
 NAME="$5"
-echo -e "\t\033[1m${NAME}\033[m: ${COLOR}${PERCENTAGE}%\033[m ${USED}/${TOTAL}\tbytes"
+echo -e "\t\033[1m${NAME}\033[m: ${COLOR}${PERCENTAGE}%\033[m \t${USED}/${TOTAL}\tbytes"
 
 exit 0
 
